# Generated by Django 5.2.3 on 2025-06-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
    ]
